const profissoes = [
    "Administrador",
    "Advogado",
    "Aeronauta",
    "Arquivista",
    "Artista",
    "Assistente Social",
    "Atleta Profissional de Futebol",
    "Bibliotecario",
    "Biomedico",
    "Biologo",
    "Bombeiro Civil",
    "Contabilista",
    "Corretor de Imoveis",
    "Corretor de Seguros",
    "Despachante Aduaneiro",
    "Engenheiro",
    "Economista Domestico",
    "Economista",
    "Empregado Domestico",
    "Enfermagem",
    "Engenharia de Seguranança",
    "Fisioterapeuta e Terapeuta Ocupacional",
    "Farmaceautico",
    "Fonoaudilogo",
    "Garimpeiro",
    "Gegrafo",
    "Gelogo",
    "Guardador e Lavador de Veiculos",
    "Instrutor de Transito",
    "Jornalista",
    "Leiloeiro",
    "Leiloeiro Rural",
    "Massagista",
    "Medico",
    "Medicina Veterinaria",
    "Mototaxista e Motoboy",
    "Muselogo",
    "Nutricionista",
    "Oceanografo",
    "Odontologia",
    "Orientador Educacional",
    "Pescador Profissional",
    "Psicologia",
    "Publicitario",
    "Radialista",
    "Representantes Comerciais",
    "Repentista",
    "Secretario",
    "Sommelier",
    "Taxista",
    "Tecnico em Administrativo",
    "Tecnico Industrial",
    "Tecnico em Pr\\u00f3tese Dent\\u00e1ria",
    "Tecnico em Radiologia",
    "Turism\\u00f3logo",
    "Zootecnista"
];

export default profissoes;